// tests/stub-generator.test.js

'use strict';

const { createTestRunner } = require('./helpers');
const { test, assert, results } = createTestRunner();
const { renderStub, isStub, makeHint } = require('../lib/stub-generator');
const { parse } = require('../lib/frontmatter');

test('renderStub preserves original name', () => {
  const out = renderStub({
    name: 'audit-pattern',
    description: 'PostToolUse hook that records every Bash execution',
    vaultPath: 'C:/Users/Vassa/.claude/lazy-skills/backups/custom/audit-pattern/SKILL.md',
  });
  const { frontmatter } = parse(out);
  assert(frontmatter.name === 'audit-pattern',
    `name changed: ${frontmatter.name}`);
});

test('renderStub description starts with [lazy] marker', () => {
  const out = renderStub({
    name: 'x',
    description: 'short',
    vaultPath: '/home/u/.claude/lazy-skills/backups/custom/x/SKILL.md',
  });
  const { frontmatter } = parse(out);
  assert(frontmatter.description.startsWith('[lazy] '),
    `missing [lazy] prefix: ${frontmatter.description}`);
});

test('renderStub description includes Vault pointer', () => {
  const out = renderStub({
    name: 'x',
    description: 'short',
    vaultPath: '/home/u/.claude/lazy-skills/backups/custom/x/SKILL.md',
  });
  const { frontmatter } = parse(out);
  assert(frontmatter.description.includes('Vault:'),
    `missing Vault pointer: ${frontmatter.description}`);
});

test('renderStub shortens long description to hint', () => {
  const longDesc = 'This is a very long description that goes well beyond the eighty character limit and should be truncated to a shorter hint for routing purposes only';
  const out = renderStub({
    name: 'x',
    description: longDesc,
    vaultPath: '/home/u/.claude/lazy-skills/backups/custom/x/SKILL.md',
  });
  const { frontmatter } = parse(out);
  // The hint should be shorter than original
  assert(frontmatter.description.length < longDesc.length + 50,
    `hint not shorter: ${frontmatter.description.length} vs ${longDesc.length}`);
  // Should contain ellipsis
  assert(frontmatter.description.includes('…'),
    `expected ellipsis in truncated hint: ${frontmatter.description}`);
});

test('renderStub body contains redirect comment with vault path', () => {
  const out = renderStub({
    name: 'x',
    description: 'short',
    vaultPath: '/home/u/.claude/lazy-skills/backups/custom/x/SKILL.md',
  });
  assert(out.includes('stub generated by lazy-skill-loader'),
    'missing generator comment');
  assert(out.includes('full content:'),
    'missing full content pointer');
  assert(out.includes('use Read tool'),
    'missing Read instruction');
});

test('isStub detects our generated stubs', () => {
  const stub = renderStub({
    name: 'x', description: 'd',
    vaultPath: '/home/u/.claude/lazy-skills/backups/custom/x/SKILL.md',
  });
  assert(isStub(stub), 'isStub should return true for our stub');
});

test('isStub returns false for original SKILL.md', () => {
  const original = `---
name: x
description: PostToolUse hook that records every Bash execution
---
# Real skill content`;
  assert(!isStub(original), 'isStub should return false for real content');
});

test('makeHint truncates at word boundary', () => {
  const longDesc = 'Word1 word2 word3 word4 word5 word6 word7 word8 word9 word10 word11 word12 word13';
  const hint = makeHint(longDesc);
  assert(hint.length < longDesc.length, 'hint should be shorter');
  // Hint ends with ellipsis on a word boundary — no partial word fragment
  assert(hint.endsWith('…'), `expected ellipsis at end, got: ${hint}`);
  // Strip ellipsis and check the last token is a complete word from the original
  const withoutEllipsis = hint.slice(0, -1);
  const lastSpace = withoutEllipsis.lastIndexOf(' ');
  const lastToken = lastSpace >= 0 ? withoutEllipsis.slice(lastSpace + 1) : withoutEllipsis;
  assert(/^[A-Za-z0-9]+$/.test(lastToken),
    `last token should be a complete word, got: "${lastToken}"`);
});

test('makeHint preserves short descriptions', () => {
  const short = 'Short description';
  assert(makeHint(short) === short, 'short description should be preserved');
});

const code = results();
process.exit(code);
